parameters:
  - name: cognitoUserPoolId
    displayName: ID of the cognito user pool
    type: string
  - name: domain
    displayName: Name of domain to create users for
    type: string
    default: expensely.io
  - name: environment
    displayName: Name of the environment
    type: string
  - name: region
    displayName: Name of the AWS region
    type: string
  - name: fileName
    displayName: Name of the CFN file to apply
    type: string

jobs:
  - job: add_cognito_users
    displayName: Add cognito ${{ parameters.fileName }}
    dependsOn: apply
    steps:
      - template: aws/iam/configure.yml@templates
      - task: PowerShell@2
        displayName: Add cognito users
        inputs:
          targetType: inline
          script: |
            aws cloudformation deploy --template-file ${{ parameters.fileName }}.yaml --stack-name expensely-${{ parameters.environment }}-cognito-${{ parameters.fileName }} --parameter-overrides CognitoUserPoolId=${{ parameters.cognitoUserPoolId }} Domain=${{ parameters.domain }} --region ${{ parameters.region }}
          errorActionPreference: stop
          showWarnings: true
          pwsh: true
          workingDirectory: $(Build.SourcesDirectory)/infrastructure
