name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: Expensely
    - repository: expensely-templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: Expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - '*'

stages:
  - stage: Production
    displayName: Production
    variables:
      - template: variables/production.ap-southeast-2.yml@expensely-templates
    jobs:
      - template: templates/release.environment.yml
        parameters:
          environment: production
          serviceConnectionName: ${{ variables.terraformServiceConnectionName }}
          stateBucketName: $(terraformStateBucketName)
          stateLockTableName: $(terraformStateLockTableName)
          region: $(region)
      - template: templates/release.environment.yml
        parameters:
          environment: production
          serviceConnectionName: ${{ variables.awsServiceConnectionName }}
          region: $(region)
          domain: expensely.io
          cognitoUserPoolId: ap-southeast-2_hZFRO90Xw
