resources:
  repositories:
    - repository: templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: Expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr: none

stages:
  - stage: build
    displayName: Build
    variables:
      - template: variables/preview.ap-southeast-2.yml@templates
    jobs:
      - job: setup
        displayName: Setup
        steps:
          - template: templates/build.number.yml

      - job: custom_message
        displayName: Custom message
        dependsOn: setup
        steps:
          - template: templates/build.lambda.yml
            parameters:
              lambdaName: custom-message

  - stage: preview
    displayName: Preview
    dependsOn:
      - build
    variables:
      - template: variables/preview.ap-southeast-2.yml@templates
    jobs:
      - template: templates/environment.release.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          region: ${{ variables.REGION }}
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users1
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users2
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users3
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users4
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users5
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users6
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users7
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users8
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users9
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg

  - stage: production
    displayName: Production
    dependsOn:
      - preview
    variables:
      - template: variables/production.ap-southeast-2.yml@templates
    jobs:
      - template: templates/environment.release.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          region: ${{ variables.REGION }}
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users1
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users2
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users3
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users4
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users5
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users6
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users7
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users8
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.ENVIRONMENT }}
          fileName: users9
          region: ${{ variables.REGION }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
