resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: Expensely
    - repository: expensely-templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: Expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - '*'

lockBehavior: runLatest
stages:
  - stage: build
    displayName: Build
    variables:
      - template: variables/preview.ap-southeast-2.yml@expensely-templates
    jobs:
      - job: setup
        displayName: Setup
        steps:
          - script: echo "##vso[build.updatebuildnumber]1.0.$(build.buildid).$(System.StageAttempt)"
            displayName: Set build identifier

      - job: custom_message
        displayName: Custom message
        dependsOn: setup
        steps:
          - template: templates/build.lambda.yml
            parameters:
              lambdaName: custom-message

  - stage: preview
    displayName: Preview
    dependsOn: []
    variables:
      - template: variables/preview.ap-southeast-2.yml@expensely-templates
    jobs:
      - template: templates/release.environment.yml
        parameters:
          environment: ${{ variables.environment }}
          serviceConnectionName: ${{ variables.terraformServiceConnectionName }}
          stateBucketName: ${{ variables.terraformStateBucketName }}
          stateLockTableName: ${{ variables.terraformStateLockTableName }}
          region: ${{ variables.region }}
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.environment }}
          serviceConnectionName: ${{ variables.awsServiceConnectionName }}
          region: ${{ variables.region }}
          cognitoUserPoolId: ap-southeast-2_Z3MVGn7hg

  - stage: production
    displayName: Production
    dependsOn: []
    variables:
      - template: variables/production.ap-southeast-2.yml@expensely-templates
    jobs:
      - template: templates/release.environment.yml
        parameters:
          environment: ${{ variables.environment }}
          serviceConnectionName: ${{ variables.terraformServiceConnectionName }}
          stateBucketName: ${{ variables.terraformStateBucketName }}
          stateLockTableName: ${{ variables.terraformStateLockTableName }}
          region: ${{ variables.region }}
      - template: templates/cognito.add-users.yml
        parameters:
          environment: ${{ variables.environment }}
          serviceConnectionName: ${{ variables.awsServiceConnectionName }}
          region: ${{ variables.region }}
          cognitoUserPoolId: ap-southeast-2_Zm4YXy0JF
