name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: Expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - '*'

stages:
  - stage: Production
    displayName: Production
    jobs:
      - template: templates/environment-release.yml
        parameters:
          environment: production
          serviceConnectionName: aws_expensely_production_ap-southeast-2
          stateBucketName: expensely-terraform-production-ap-southeast-2
          stateLockTableName: expensely-terraform-lock-production-ap-southeast-2
