environment="Preview"
region="ap-southeast-2"
cognito_user_pool_name="expensely-preview"
cognito_from_email_address="no-reply@preview.expensely.app"
cognito_client_app_domain="preview.expensely.app"
cognito_configuration_set="expensely-preview"
custom_message_default_uri="https://preview.expensely.app"
custom_message_log_level="default"